[package]
name = "lecture-analyzer2"
version = "0.1.0"
edition = "2024"

[dependencies]
pdf-extract = "0.6"           # simple PDF text extraction (wrapper around poppler-utils)
lopdf = "0.31"                # alternative: low-level PDF parsing

# Natural language processing
regex = "1.10"                # for cleaning text / splitting
lazy_static = "1.5"           # for precompiled regex patterns
stopwords = "0.3"             # common stopword lists (for RAKE)

# Graph + algorithms (for TextRank)
petgraph = "0.6"              # graph library for TextRank

# Exporting to PDF
printpdf = "0.7"              # create structured PDFs with formatting
# OR: genpdf = "0.8"           # easier API if you want simple text PDFs

# Utilities
reqwest = { version = "0.12", features = ["blocking"] } # fetch reference links (blocking for CLI)
scraper = "0.19"              # HTML parsing for utils.rs if you scrape links
anyhow = "1.0"                # error handling
thiserror = "1.0"             # custom error types

# Optional: logging
log = "0.4"
env_logger = "0.11"